"""empty message

Revision ID: 540f8107e212
Revises: 9aa3a5618ea4
Create Date: 2020-06-18 19:37:40.639818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540f8107e212'
down_revision = '9aa3a5618ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=35), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
