"""empty message

Revision ID: 9aa3a5618ea4
Revises: 485b08a73943
Create Date: 2020-06-17 20:28:45.756316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa3a5618ea4'
down_revision = '485b08a73943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pswd_hashed', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pswd_hashed')
    # ### end Alembic commands ###
